---
# Checksum and its related algorithm documented at: https://www.packer.io/downloads.html
- name: Downloading the Packer installation file
  get_url:
    url: "{{ install_packer_in_linux_url }}"
    dest: "/tmp/{{ install_packer_in_linux_file }}"
    checksum: "sha256:{{ install_packer_in_linux_checksum }}"
  become: yes

- name: Extracting the Packer installation file
  unarchive:
    src: "/tmp/{{ install_packer_in_linux_file }}"
    dest: /usr/local/bin
  become: yes
