---
dependencies:
  - role: install-packages-in-linux
    vars:
      install_packages_in_linux_packages:
        - python2
        - python-pip

  - role: install-packages-with-pip
    vars:
      install_packages_with_pip_packages:
        - boto
        - boto3
        - botocore
