---
- name: Disabling unused filesystems
  block:
    # 1.1.1.1 Ensure mounting of cramfs filesystems is disabled
    - name: "Applying recommendation 1.1.1.1: Disabling cramfs"
      lineinfile:
        path: "{{ apply_cis_benchmarks_modprobe_conf }}"
        line: install cramfs /bin/true
        create: true

    # 1.1.1.2 Ensure mounting of freevxfs filesystems is disabled
    - name: "Applying recommendation 1.1.1.2: Disabling freevxfs"
      lineinfile:
        path: "{{ apply_cis_benchmarks_modprobe_conf }}"
        line: install freevxfs /bin/true
        create: true

    # 1.1.1.3 Ensure mounting of jffs2 filesystems is disabled
    - name: "Applying recommendation 1.1.1.3: Disabling jffs2"
      lineinfile:
        path: "{{ apply_cis_benchmarks_modprobe_conf }}"
        line: install jffs2 /bin/true
        create: true

    # 1.1.1.4 Ensure mounting of hfs filesystems is disabled
    - name: "Applying recommendation 1.1.1.4: Disabling hfs"
      lineinfile:
        path: "{{ apply_cis_benchmarks_modprobe_conf }}"
        line: install hfs /bin/true
        create: true

    # 1.1.1.5 Ensure mounting of hfsplus filesystems is disabled
    - name: "Applying recommendation 1.1.1.5: Disabling hfsplus"
      lineinfile:
        path: "{{ apply_cis_benchmarks_modprobe_conf }}"
        line: install hfsplus /bin/true
        create: true

    # 1.1.1.6 Ensure mounting of squashfs filesystems is disabled
    - name: "Applying recommendation 1.1.1.6: Disabling squashfs"
      lineinfile:
        path: "{{ apply_cis_benchmarks_modprobe_conf }}"
        line: install squashfs /bin/true
        create: true

    # 1.1.1.7 Ensure mounting of udf filesystems is disabled
    - name: "Applying recommendation 1.1.1.7: Disabling udf"
      lineinfile:
        path: "{{ apply_cis_benchmarks_modprobe_conf }}"
        line: install udf /bin/true
        create: true

    # 1.1.1.8 Ensure mounting of vfat filesystems is disabled
    - name: "Applying recommendation 1.1.1.8: Disabling vfat"
      lineinfile:
        path: "{{ apply_cis_benchmarks_modprobe_conf }}"
        line: install vfat /bin/true
        create: true

  become: true
