# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.define "ubuntu1404" do |ubuntu1404|
    ubuntu1404.vm.box = "ubuntu/trusty64"
    ubuntu1404.vm.provision "shell", inline: <<-SHELL
      export LANGUAGE=en_US.UTF-8
      export LANG=en_US.UTF-8
      export LC_ALL=en_US.UTF-8
      locale-gen en_US.UTF-8
      dpkg-reconfigure locales
      apt update
      apt install -y libffi-dev libssl-dev python-dev python-pip
      pip install setuptools>=18.5 --upgrade
      pip install ansible
    SHELL
  end

  config.vm.define "ubuntu1604" do |ubuntu1604|
    ubuntu1604.vm.box = "ubuntu/xenial64"
    ubuntu1604.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y python-pip
      pip install ansible
    SHELL
  end

  config.vm.define "ubuntu1804" do |ubuntu1804|
    ubuntu1804.vm.box = "ubuntu/bionic64"
    ubuntu1804.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install -y python-pip
      pip install ansible
    SHELL
  end

  config.vm.synced_folder "../../", "/vagrant", type: "rsync"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 2048
    # Disabling log generation
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
  end

end
