---
- name: Preparing Molecule instance
  hosts: all
  gather_facts: false
  tasks:
    - block:
        - name: Installing python-apt
          shell:
            apt update -y && apt install -y python-apt

        - name: Installing dependencies
          apt:
            name:
              - apt
              - kmod
            force_apt_get: true

        - name: Restarting to apply changes to the kernel
          reboot:

      become: true
